### ISSUE TITLE
Work on `TODO`s

### ISSUE THREAD

**Issue by fhagemann** [mppmu/GeDetComptonScatteringAnalysis.jl#15]
Some parts of the codes have TODOs implemented as comments.
This is a meta issue to address all of them:

- [ ] Add flag to rely more on DAQ_energies or camera energies in `get_z_from_energies`:
https://github.com/mppmu/GeDetComptonScatteringAnalysis.jl/blob/533d92ef279066733a8fc756bfe0dc8f657aa634/src/compton_scanner_analysis.jl#L34-L45
- [ ] Improve `getz` (see also #11):
https://github.com/mppmu/GeDetComptonScatteringAnalysis.jl/blob/533d92ef279066733a8fc756bfe0dc8f657aa634/src/compton_scanner_analysis.jl#L144-L153
- [ ] Fix transformations and restructure `merge_data` (see also #13):
https://github.com/mppmu/GeDetComptonScatteringAnalysis.jl/blob/533d92ef279066733a8fc756bfe0dc8f657aa634/src/stack_and_merge.jl#L37-L40
- [ ] At the end of `merge_data`:
https://github.com/mppmu/GeDetComptonScatteringAnalysis.jl/blob/533d92ef279066733a8fc756bfe0dc8f657aa634/src/stack_and_merge.jl#L109-L110
